<#
.SYNOPSIS
    Post-setup script for Windsurf Git Worktrees.
    Copies essential untracked files into each new worktree directory.

.DESCRIPTION
    Executed automatically by Windsurf via post_setup_worktree hook.
    - Copies .planning/ directory (read-only reference for the agent)
    - Copies .env files if they exist
    - Sets CARGO_TARGET_DIR to share Rust build cache across worktrees
    - Logs worktree creation for tracking

.NOTES
    The $ROOT_WORKSPACE_PATH env var points to the original workspace.
    This script runs inside the NEW worktree directory.
#>

$ErrorActionPreference = "Stop"

$rootPath = $env:ROOT_WORKSPACE_PATH
if (-not $rootPath) {
    Write-Error "ROOT_WORKSPACE_PATH not set. Aborting worktree setup."
    exit 1
}

$worktreePath = Get-Location
Write-Host "[worktree-setup] Initializing worktree at: $worktreePath"
Write-Host "[worktree-setup] Root workspace: $rootPath"

# --- Copy .planning/ directory (read-only reference for agent context) ---
$planningSource = Join-Path $rootPath ".planning"
if (Test-Path $planningSource) {
    $planningDest = Join-Path $worktreePath ".planning"
    Copy-Item -Path $planningSource -Destination $planningDest -Recurse -Force
    Write-Host "[worktree-setup] Copied .planning/ directory"
} else {
    Write-Host "[worktree-setup] No .planning/ directory found, skipping"
}

# --- Copy .env files (secrets not tracked by git) ---
$envFiles = @(".env", ".env.local", ".env.development")
foreach ($envFile in $envFiles) {
    $envSource = Join-Path $rootPath $envFile
    if (Test-Path $envSource) {
        Copy-Item -Path $envSource -Destination (Join-Path $worktreePath $envFile) -Force
        Write-Host "[worktree-setup] Copied $envFile"
    }
}

# --- Rust: share target/ directory to avoid full rebuild per worktree ---
$cargoToml = Join-Path $worktreePath "Cargo.toml"
if (Test-Path $cargoToml) {
    $sharedTarget = Join-Path $rootPath "target"
    # Reason: CARGO_TARGET_DIR avoids duplicating ~GB of build artifacts per worktree
    $env:CARGO_TARGET_DIR = $sharedTarget
    # Also write a .cargo/config.toml so cargo picks it up in subsequent runs
    $cargoConfigDir = Join-Path $worktreePath ".cargo"
    if (-not (Test-Path $cargoConfigDir)) {
        New-Item -ItemType Directory -Path $cargoConfigDir -Force | Out-Null
    }
    $cargoConfigFile = Join-Path $cargoConfigDir "config.toml"
    # Only write if not already present (don't overwrite user config)
    if (-not (Test-Path $cargoConfigFile)) {
        @"
# Auto-generated by worktree setup hook
# Shares build cache with main workspace to save disk space
[build]
target-dir = "$($sharedTarget -replace '\\', '/')"
"@ | Set-Content -Path $cargoConfigFile -Encoding UTF8
        Write-Host "[worktree-setup] Created .cargo/config.toml with shared target-dir"
    } else {
        Write-Host "[worktree-setup] .cargo/config.toml already exists, skipping"
    }
}

# --- Log worktree creation ---
$logFile = Join-Path $rootPath ".planning" "worktree-log.txt"
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$logEntry = "$timestamp | CREATED | $worktreePath"
if (Test-Path (Split-Path $logFile -Parent)) {
    Add-Content -Path $logFile -Value $logEntry -Encoding UTF8
    Write-Host "[worktree-setup] Logged creation to .planning/worktree-log.txt"
}

Write-Host "[worktree-setup] Worktree setup complete."
exit 0
