#!/usr/bin/env python3
"""Generate a lightweight performance proof-pack markdown from benchmark JSON."""

from __future__ import annotations

import json
import pathlib
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parents[1]
INPUT = ROOT / "benchmarks" / "proofpack-sample.json"
OUTPUT = ROOT / "docs" / "reference" / "performance-proofpack.md"


def format_row(name: str, p50: float, p95: float, p99: float, recall: float) -> str:
    return f"| {name} | {p50:.2f} | {p95:.2f} | {p99:.2f} | {recall:.2f}% |"


def main() -> int:
    data = json.loads(INPUT.read_text(encoding="utf-8"))
    rows = [
        format_row(item["profile"], item["p50_ms"], item["p95_ms"], item["p99_ms"], item["recall_at_10"])
        for item in data["profiles"]
    ]

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    md = [
        "# Performance SLO Proof-Pack",
        "",
        f"Generated: {now}",
        "",
        "| Profile | p50 (ms) | p95 (ms) | p99 (ms) | Recall@10 |",
        "|---|---:|---:|---:|---:|",
        *rows,
        "",
        "## Notes",
        "",
        "- This file is generated by `scripts/generate-performance-proofpack.py`.",
        "- In CI/release, replace `benchmarks/proofpack-sample.json` with measured benchmark export.",
    ]

    OUTPUT.write_text("\n".join(md) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
